@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbHQyIiwiaWF0IjoxNjg3NDEwODIzLCJleHAiOjE2ODc0MTA4ODN9.FS6zqn61TB6QQFEYkQccnFwYk6_wrzFQWcdeojgLiwY

POST http://127.0.0.1:3000/auth
Content-Type: application/json

{"user":"walt1","pwd":"Aa$12345"}
###

GET http://127.0.0.1:3000/refresh
Content-Type: application/json

{"user":"walt1","pwd":"Aa$12345"}
###

GET http://127.0.0.1:3000/employees
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
###

POST http://127.0.0.1:3000/employees
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{"firstname":"Mwamuzi","lastname":"Shada"}